{
 "title": "PimpMySuperWatt",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pimpMySuperWattUrl",
    "query": "show tag values from \"pimpMySuperWatt\" with key = \"url\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "content": "\n# PimpMySuperWatt Grafana Panel\n**Coxifred 2020**\n[GitHub Project](https://github.com/coxifred/pimpMySuperWatt).\n\n\n"
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 0 },
   "content": "<br>\n<a href=${pimpMySuperWattUrl} target=new >Go to PimpMySuperWatt Interface</a>\n<br>\n<img height=200px src=${pimpMySuperWattUrl}/static/images/pimpMySuperWatt.png>"
  },
  {
   "title": "(AC Watt - PV Watt)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT ac_watt - pv_watts as \"value\" FROM \"pimpMySuperWatt\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Watts Informations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT \"pv_watts\" FROM \"pimpMySuperWatt\" WHERE $timeFilter GROUP BY  \"instance\"",
     "select": [
      [
       { "params": [ "pv_watts" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$tag_instance $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT \"ac_watt\" FROM \"pimpMySuperWatt\" WHERE $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "ac_watt" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Parameters",
   "type": "table",
   "gridPos": { "h": 19, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt_Parameters",
     "query": "SELECT last(*) FROM \"pimpMySuperWatt_Parameters\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "instance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT last(\"load_percent\") FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT last(\"temp\") FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 9 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT \"pv_volts\" FROM \"pimpMySuperWatt\" WHERE $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "pv_volts" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp and Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $col",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT \"pv_volts\" FROM \"pimpMySuperWatt\" WHERE $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$tag_instance $col",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT \"pv_volts\" FROM \"pimpMySuperWatt\" WHERE $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Watts - PV Watts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 16 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $col",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT ac_watt - pv_watts as \"value\" FROM \"pimpMySuperWatt\" WHERE $timeFilter group by \"instance\"",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Voltage & Frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $col",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT \"pv_volts\" FROM \"pimpMySuperWatt\" WHERE $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "ac_volt" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$tag_instance $col",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT \"pv_volts\" FROM \"pimpMySuperWatt\" WHERE $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "ac_freq" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}