{
 "title": "PimpMySuperWatt",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pimpMySuperWattUrl",
    "query": "show tag values from \"pimpMySuperWatt\" with key = \"url\""
   },
   { "name": "DS_PIMPMYSUPERWATT", "query": "pimpMySuperWatt" }
  ]
 },
 "panels": [
  { "title": "Quick stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 1 },
   "options": {
    "content": "\n# PimpMySuperWatt Grafana Panel\n**Coxifred 2020**\n[GitHub Project](https://github.com/coxifred/pimpMySuperWatt)."
   },
   "targets": [
    {}
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 } },
  {
   "type": "text",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 1 },
   "options": {
    "content": "<a href=https://github.com/coxifred/pimpMySuperWatt target=new style=font-size:0.7em>Go to PimpMySuperWatt Interface</a>\n<img src=https://github.com/coxifred/pimpMySuperWatt/blob/master/doc/pimpMySuperWatt2.png?raw=true>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pv Status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "Pv loss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_pvLoss" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Bus Over",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_busOver" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Bus Under",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_busUnder" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Bus Soft Fail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_busSoftFail" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Opv Short",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_opvShort" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 6 },
   "targets": [
    {
     "alias": "Low Alarm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_batteryLowAlarm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Voltage High",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_batteryVoltageHigh" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Under Shutdown",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_batteryUnderShutdown" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Derating",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_batteryDerating" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Open",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_batOpen" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Weak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_batteryWeak" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Equalization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_batteryEqualization" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "Bus Line Fail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_lineFail" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Voltage too low",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_inverterVoltageTooLow" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Voltage too high",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_inverterVoltageTooHigh" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Over temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_overTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Fan locked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_fanLocked" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Overload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_overload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Eeprom Fault",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_eepromFault" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Over current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_inverterOverCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Soft fail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_inverterSoftFail" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Self test fail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_selfTestFail" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "OPDC voltage over",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_opDcVoltageOver" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Current Sensor fail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpiws_currentSensorFail" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Watt Array 1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "pimpMySuperWatt",
     "query": "SELECT max(\"pv_watts\") FROM \"pimpMySuperWatt\" WHERE (\"array\"::tag = '1') AND time > now() - 60m",
     "select": [
      [
       { "params": [ "qpigs_pv_watts" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Watt Array 2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT max(\"pv_watts\") FROM \"pimpMySuperWatt\" WHERE (\"array\"::tag = '2') AND time > now() - 60m ",
     "select": [
      [
       { "params": [ "qpigs2_pv2_watts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT max(\"pv_watts\") FROM \"pimpMySuperWatt\" WHERE (\"array\"::tag = '2') AND time > now() - 60m ",
     "select": [
      [
       { "params": [ "qpigs_batt_capacity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT last(\"qpigs_temp\") FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Production by periods",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Day production",
     "measurement": "pimpMySuperWatt",
     "query": "SELECT \"qed_day_production\" FROM \"pimpMySuperWatt\" where time > now() - 165d order by time",
     "select": [
      [
       { "params": [ "day_production" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Month production",
     "measurement": "pimpMySuperWatt",
     "query": "SELECT \"qem_month_production\" FROM \"pimpMySuperWatt\" where time > now() - 165d order by time",
     "select": [
      [
       { "params": [ "month_production" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Year production",
     "measurement": "pimpMySuperWatt",
     "query": "SELECT max(\"qey_year_production\") FROM \"pimpMySuperWatt\"  where time > now() - 165d order by time",
     "select": [
      [
       { "params": [ "year_production" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GRID consumption by periods",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Day consumption",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT sum(\"gridwatts\") FROM \"pimpMySuperWatt\" WHERE $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "gridwatts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT last(\"qpigs_load_percent\") FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "On inverter Consumption",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "last",
     "measurement": "pimpMySuperWatt",
     "query": "SELECT max(\"pv_watts\") FROM \"pimpMySuperWatt\" WHERE (\"array\"::tag = '2') AND time > now() - 60m ",
     "select": [
      [
       { "params": [ "qpigs_ac_watt" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "watts1",
     "measurement": "pimpMySuperWatt",
     "query": "SELECT max(\"pv_watts\") FROM \"pimpMySuperWatt\" WHERE (\"array\"::tag = '2') AND time > now() - 60m ",
     "select": [
      [
       { "params": [ "qpigs_pv_watts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "watts2",
     "measurement": "pimpMySuperWatt",
     "query": "SELECT max(\"pv_watts\") FROM \"pimpMySuperWatt\" WHERE (\"array\"::tag = '2') AND time > now() - 60m ",
     "select": [
      [
       { "params": [ "qpigs2_pv2_watts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid Consumption",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "last",
     "measurement": "pimpMySuperWatt",
     "query": "SELECT max(\"pv_watts\") FROM \"pimpMySuperWatt\" WHERE (\"array\"::tag = '2') AND time > now() - 60m ",
     "select": [
      [
       { "params": [ "gridwatts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Warnings & Faults History 0->OK, 1->WNG, 2->FAULT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overload Trace",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 29 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_overload\"  FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "PvLoss",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 29 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_pvLoss\" FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Inverter Fault",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 29 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_inverterFault\" FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Bus Over",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 29 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_busOver\" FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Bus Under",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 29 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_busUnder\" FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Bus Soft Fail",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 29 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_busSoftFail\" FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Line Fail",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 33 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_lineFail\"  FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "OPV Short",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 33 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_opvShort\" FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Inverter Voltage too low",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 33 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_inverterVoltageTooLow\" FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Inverter Voltage too high",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 33 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_inverterVoltageTooHigh\"  FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Over temperature",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 33 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_overTemperature\" FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Fan locked",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 33 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_fanLocked\" FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Battery voltage high",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 37 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_batteryVoltageHigh\"  FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Battery Low Alarm",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 37 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_batteryLowAlarm\" FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Battery under shutdown",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 37 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_batteryUnderShutdown\"  FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Battery derating",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 37 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_batteryDerating\"  FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Inverter over current",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 37 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_inverterOverCurrent\" FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Inverter soft fail",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 37 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_inverterSoftFail\" FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Self test fail",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 41 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_selfTestFail\" FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "OPDC Voltage over",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 41 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_opDcVoltageOver\" FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Battery open",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 41 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_batOpen\"  FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Current Sensor Fail",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 41 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_currentSensorFail\"  FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Battery Equalization",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 41 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_batteryEqualization\"  FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Battery Weak",
     "type": "logs",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 41 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT \"qpiws_batteryWeak\"  FROM \"pimpMySuperWatt\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "qpiws_overload" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Battery stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Battery Voltage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "Voltage",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pimpMySuperWatt",
       "select": [
        [
         { "params": [ "qpigs_batt_volt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Battery Charge Amperes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 10, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "alias": "charge",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pimpMySuperWatt",
       "select": [
        [
         { "params": [ "qpigs_batt_charge_amps" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "discharge",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pimpMySuperWatt",
       "select": [
        [
         { "params": [ "qpigs_batt_discharge_amps" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Battery Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "Capacity",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pimpMySuperWatt",
       "select": [
        [
         { "params": [ "qpigs_batt_capacity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Production/Consumptions curves & ranks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Solar Production Array1 + Array2 by Zenith & Azimuth",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 13, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "alias": "Array 1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "select": [
        [
         { "params": [ "qpigs_pv_watts" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "alias": "zenith",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt_plugin_solarPosition",
       "query": "SELECT mean(\"zenith\") AS \"zenith\" FROM \"pimpMySuperWatt_plugin_solarPosition\" WHERE $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "zenith" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "alias": "azimuth",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt_plugin_solarPosition",
       "query": "SELECT mean(\"zenith\") AS \"zenith\" FROM \"pimpMySuperWatt_plugin_solarPosition\" WHERE $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "azimuth" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "alias": "Grid consumption",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT max(\"watts\") FROM \"consommationMaison\" WHERE (\"localisation\"::tag = 'Compteur_EDF_from_Shelly') AND $timeFilter GROUP BY time($interval)",
       "select": [
        [
         { "params": [ "gridwatts" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "alias": "Consumption on inverter",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "query": "SELECT max(\"watts\") FROM \"consommationMaison\" WHERE (\"localisation\"::tag = 'Compteur_EDF_from_Shelly') AND $timeFilter GROUP BY time($interval)",
       "select": [
        [
         { "params": [ "qpigs_ac_watt" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "alias": "Array 2",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "select": [
        [
         { "params": [ "qpigs2_pv2_watts" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Best rank watts array 1",
     "type": "table",
     "gridPos": { "h": 7, "w": 7, "x": 13, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "60m" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" }
       ],
       "limit": "10",
       "measurement": "pimpMySuperWatt",
       "query": "SELECT max(\"pv_watts\") FROM \"pimpMySuperWatt\" WHERE (\"array\"::tag = '1') AND $timeFilter GROUP BY time($__interval), \"instance\", \"array\"::tag",
       "select": [
        [
         { "params": [ "qpigs_pv_watts" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Best rank watts array 2",
     "type": "table",
     "gridPos": { "h": 7, "w": 7, "x": 13, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "60m" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" }
       ],
       "limit": "10",
       "measurement": "pimpMySuperWatt",
       "query": "SELECT max(\"pv_watts\") FROM \"pimpMySuperWatt\" WHERE (\"array\"::tag = '1') AND $timeFilter GROUP BY time($__interval), \"instance\", \"array\"::tag",
       "select": [
        [
         { "params": [ "qpigs2_pv2_watts" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "array::tag", "operator": "=", "value": "2" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Monitoring Voltage/Freq/Temp/Load/Parameters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Parameters (Last value)",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt_Parameters",
     "query": "SELECT  last(*) FROM \"pimpMySuperWatt_Parameters\" where time > now() - 1m",
     "select": [
      [
       { "params": [ "instance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Parameters on timerange",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt_Parameters",
     "query": "SELECT  * FROM \"pimpMySuperWatt_Parameters\" where $timeFilter",
     "select": [
      [
       { "params": [ "instance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp and Load",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_instance $col",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT \"pv_volts\" FROM \"pimpMySuperWatt\" WHERE $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "qpigs_temp" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$tag_instance $col",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT \"pv_volts\" FROM \"pimpMySuperWatt\" WHERE $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "qpigs_load_percent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Array 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpigs_pv_volts" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Array 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpigs2_pv2_watts" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Voltage",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "targets": [
    {
     "alias": "$tag_instance ac_volt_output",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT \"ac_volt\" FROM \"pimpMySuperWatt\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "qpigs_ac_volt" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "$tag_instance ac_volt_input",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "query": "SELECT \"ac_volt\" FROM \"pimpMySuperWatt\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "qpigs_grid_volt" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AC Frequency",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "alias": "$tag_instance ac_freq output",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pimpMySuperWatt",
     "select": [
      [
       { "params": [ "qpigs_ac_freq" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Behaviour Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Battery Charge Amperes",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "alias": "charge",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pimpMySuperWatt",
       "select": [
        [
         { "params": [ "qpigs_batt_charge_amps" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "discharge",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pimpMySuperWatt",
       "select": [
        [
         { "params": [ "qpigs_batt_discharge_amps" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "battery capacity",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "select": [
        [
         { "params": [ "qpigs_batt_capacity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "compteur EDF",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "select": [
        [
         { "params": [ "gridwatts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "pv1",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "select": [
        [
         { "params": [ "qpigs_pv_watts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "pv2",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "select": [
        [
         { "params": [ "qpigs2_pv2_watts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "demande sur onduleur",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "pimpMySuperWatt",
       "select": [
        [
         { "params": [ "qpigs_ac_watt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "volt batt",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "pimpMySuperWatt",
       "select": [
        [
         { "params": [ "qpigs_batt_volt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}